### ISSUE TITLE
pysaliency roc not found

### ISSUE THREAD

**Issue by fwahhab89** [matthias-k/pysaliency#5]
I installed the pysaliency module. But I still have the issue:

File "/home/pysaliency-master/pysaliency/init.py", line 8, in
from .saliency_map_models import SaliencyMapModel, GeneralSaliencyMapModel, FixationMap
File "/home/pysaliency-master/pysaliency/saliency_map_models.py", line 13, in
from .roc import general_roc
ImportError: No module named roc

I am using python2.7 on a ubuntu system.

**Comment by ysyscool** [comment]
I have the same questions. Does anyone solve this?

**Comment by matthias-k** [comment]
Hi @fwahhab89,

thanks for the report and sorry for the delay. Could it be that you are executing python from within the pysaliency directory? I had problems like these in this case too. I just tried installing pysaliency into a fresh virtual environment and I could import the roc function afterwarts.

Otherwise, you could try executing `python setup.py build_ext --inplace`, which should create the roc library within the source code. Then importing pysaliency from within the source directory should work, too.
